# Generated by Django 5.2.9 on 2025-12-04 15:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'verbose_name': 'Avaliação', 'verbose_name_plural': 'Avaliações'},
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='professores',
            field=models.ManyToManyField(blank=True, limit_choices_to={'tipo': 'PROFESSOR'}, related_name='disciplinas', to=settings.AUTH_USER_MODEL),
        ),
    ]
