# Generated by Django 5.2.9 on 2025-12-04 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_avaliacao_options_alter_disciplina_professores"),
    ]

    operations = [
        migrations.AddField(
            model_name="avaliacao",
            name="tipo_avaliador",
            field=models.CharField(
                choices=[("ALUNO", "Aluno"), ("PROFESSOR", "Professor")],
                default="ALUNO",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="avaliacao",
            name="agendamento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.agendamento"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="avaliacao",
            unique_together={("agendamento", "tipo_avaliador")},
        ),
    ]
